global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-2
        access_key: AKIA274JOTM3SQHMODBK
        secret_key: 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
        port: 9100
